stages:
  preprocess:
    cmd: python model/preprocess.py
    deps:
      - model/preprocess.py
      - backend/parser.py
    outs:
      - data/processed/

  train:
    cmd: python model/train.py
    deps:
      - model/train.py
      - data/processed/
    outs:
      - model/model.pkl